<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { RouterLink, useRoute, useRouter } from "vue-router";
import axios from "axios";
import AppPageHeader from "../components/AppPageHeader.vue";
import ReviewDocumentPreview from "../components/ReviewDocumentPreview.vue";
interface Lesson { id:string;title:string;subject:string;grade:string;topic:string;currentVersionId:string;updatedAt:string }
interface Version { id:string;versionNumber:number;content:string;sourceModule:string;createdAt:string }
interface Detail { lesson:Lesson;versions:Version[] }
interface SourceDoc { originalFilename:string;sizeBytes:number;createdAt:string }
const route=useRoute(),router=useRouter();const list=ref<Lesson[]>([]),detail=ref<Detail|null>(null),source=ref<SourceDoc|null>(null);const selectedId=ref(""),loading=ref(false),error=ref("");
const lessonId=computed(()=>String(route.params.lessonId||""));const selected=computed(()=>detail.value?.versions.find(item=>item.id===selectedId.value)||null);const exportUrl=computed(()=>lessonId.value&&selectedId.value?`/api/platform/lessons/${encodeURIComponent(lessonId.value)}/versions/${encodeURIComponent(selectedId.value)}/export/docx`:"");
const sourceNames:Record<string,string>={IMPORT_DOCX:"DOCX导入",IMPORT_TEXT:"文本创建",MANUAL:"手动修改",F1_ANNOTATION:"智能评价",F2_OPTIMIZATION:"设计修改",F2_OPTIMIZE:"设计修改",F3_SIMULATION:"课堂推演",F4_NAVIGATION:"协同共析"};
function describe(reason:unknown){return axios.isAxiosError(reason)?((reason.response?.data as {detail?:string})?.detail||reason.message):String(reason)}
function formatTime(value:string){return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value))}
function formatBytes(value:number){return value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`}
async function loadList(){loading.value=true;try{list.value=(await axios.get<Lesson[]>("/api/platform/lessons")).data}catch(reason){error.value=describe(reason)}finally{loading.value=false}}
async function loadDetail(id:string){if(!id){detail.value=null;return}loading.value=true;error.value="";try{detail.value=(await axios.get<Detail>(`/api/platform/lessons/${encodeURIComponent(id)}`)).data;const requested=typeof route.query.version==="string"?route.query.version:"";selectedId.value=detail.value.versions.some(v=>v.id===requested)?requested:detail.value.lesson.currentVersionId;source.value=await axios.get<SourceDoc>(`/api/platform/lessons/${encodeURIComponent(id)}/source-document`).then(r=>r.data).catch(()=>null)}catch(reason){error.value=describe(reason)}finally{loading.value=false}}
function selectVersion(id:string){selectedId.value=id;void router.replace({query:{...route.query,version:id}})}
onMounted(()=>{void loadList()});watch(lessonId,id=>{void loadDetail(id)},{immediate:true});
</script>

<template><main class="lessons-page">
  <AppPageHeader title="我的教案" :description="lessonId?'查看教案正文、版本来源与下载文件。':'集中管理已导入或生成的教案。上传新教案请返回首页。'"><template #actions><RouterLink v-if="lessonId" class="v2-button v2-button--secondary" to="/lessons">返回教案列表</RouterLink><RouterLink v-else class="v2-button v2-button--primary" to="/">上传或生成教案</RouterLink></template></AppPageHeader>
  <p v-if="error" class="error" role="alert">{{ error }}</p>
  <template v-if="!lessonId"><section v-if="list.length" class="lesson-grid"><RouterLink v-for="lesson in list" :key="lesson.id" :to="`/lessons/${lesson.id}`" class="lesson-card v2-card"><div><small>{{ [lesson.subject,lesson.grade].filter(Boolean).join(' · ')||'教案' }}</small><h2>{{ lesson.title }}</h2><p>{{ lesson.topic||'未填写课题' }}</p></div><footer><span>更新于 {{ formatTime(lesson.updatedAt) }}</span><b>查看详情 →</b></footer></RouterLink></section><section v-else-if="!loading" class="empty v2-card"><h2>还没有教案</h2><p>从首页上传 DOCX，或使用设计修改功能生成第一份教案。</p><RouterLink class="v2-button v2-button--primary" to="/">返回首页</RouterLink></section><p v-else class="loading">正在读取教案……</p></template>
  <template v-else-if="detail"><section class="detail-layout"><aside class="version-panel v2-card"><div><small>版本历史</small><h2>{{ detail.lesson.title }}</h2><p>{{ detail.versions.length }} 个版本</p></div><button v-for="version in [...detail.versions].sort((a,b)=>b.versionNumber-a.versionNumber)" :key="version.id" type="button" :class="{selected:selectedId===version.id}" @click="selectVersion(version.id)"><b>V{{ version.versionNumber }}</b><span>{{ sourceNames[version.sourceModule]||version.sourceModule }}</span><small>{{ formatTime(version.createdAt) }}</small></button></aside>
    <section class="content-panel v2-card"><header><div><small>{{ selected?`V${selected.versionNumber} · ${sourceNames[selected.sourceModule]||selected.sourceModule}`:'' }}</small><h2>{{ detail.lesson.title }}</h2><p>{{ selected?`创建于 ${formatTime(selected.createdAt)}`:'' }}</p></div><a v-if="exportUrl" class="v2-button v2-button--primary" :href="exportUrl" download>下载 DOCX</a></header><div v-if="source" class="source-note"><span>原始文件：{{ source.originalFilename }} · {{ formatBytes(source.sizeBytes) }}</span><a :href="`/api/platform/lessons/${encodeURIComponent(lessonId)}/source-document/file`">下载原稿</a></div><ReviewDocumentPreview :content="selected?.content||''" /></section></section>
    <section class="next-actions v2-card"><div><small>继续处理</small><h2>使用当前版本</h2></div><RouterLink :to="{path:'/workflows',query:{lessonId,versionId:selectedId}}">选择工作流</RouterLink><RouterLink :to="{path:`/lessons/${lessonId}/annotate`,query:{version:selectedId}}">智能评价</RouterLink><RouterLink :to="{path:'/optimize-lesson',query:{lessonId,versionId:selectedId}}">设计修改</RouterLink><RouterLink :to="{path:'/simulate',query:{lessonId,versionId:selectedId}}">课堂推演</RouterLink><RouterLink :to="{path:'/navigation',query:{lessonId,versionId:selectedId}}">协同共析</RouterLink></section>
  </template>
</main></template>

<style scoped>
.lessons-page{display:grid;gap:22px}.error{padding:13px;border-radius:var(--radius-sm);color:var(--color-danger);background:var(--color-danger-soft)}.lesson-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.lesson-card{min-height:180px;display:flex;flex-direction:column;justify-content:space-between;padding:22px;color:var(--color-text)}.lesson-card:hover{border-color:var(--color-primary-border);box-shadow:var(--shadow-card)}.lesson-card small{color:var(--color-primary);font-weight:700}.lesson-card h2{margin:10px 0 6px;font-size:19px}.lesson-card p,.lesson-card footer span{color:var(--color-text-secondary)}.lesson-card footer{display:flex;justify-content:space-between;gap:14px;font-size:12px}.lesson-card footer b{color:var(--color-primary)}.empty{text-align:center;padding:48px}.empty p,.loading{color:var(--color-text-secondary)}.detail-layout{display:grid;grid-template-columns:260px minmax(0,1fr);align-items:start;gap:18px}.version-panel{overflow:hidden}.version-panel>div{padding:20px}.version-panel>div small,.content-panel header small,.next-actions small{color:var(--color-primary);font-weight:800}.version-panel h2{margin:7px 0;font-size:18px}.version-panel p{margin:0;color:var(--color-text-muted);font-size:13px}.version-panel>button{width:100%;display:grid;grid-template-columns:45px 1fr;gap:4px 8px;padding:14px 18px;border:0;border-top:1px solid var(--color-border);background:#fff;text-align:left;cursor:pointer}.version-panel>button.selected{background:var(--color-primary-soft)}.version-panel button b{grid-row:1/3;color:var(--color-primary)}.version-panel button span{font-size:13px;font-weight:700}.version-panel button small{color:var(--color-text-muted)}.content-panel{overflow:hidden}.content-panel>header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:22px;border-bottom:1px solid var(--color-border)}.content-panel h2{margin:6px 0}.content-panel header p{margin:0;color:var(--color-text-muted);font-size:12px}.source-note{display:flex;justify-content:space-between;gap:15px;padding:12px 22px;color:var(--color-text-secondary);background:var(--color-surface-soft);font-size:12px}.source-note a{color:var(--color-primary);font-weight:700}.content-panel :deep(.review-paper){min-height:400px;padding:clamp(26px,4vw,54px);border:0}.next-actions{display:flex;align-items:center;gap:10px;padding:17px 20px}.next-actions>div{margin-right:auto}.next-actions h2{margin:3px 0;font-size:17px}.next-actions>a{padding:9px 12px;border:1px solid var(--color-primary-border);border-radius:var(--radius-md);color:var(--color-primary);font-size:13px;font-weight:700}@media(max-width:1000px){.lesson-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.detail-layout{grid-template-columns:1fr}.next-actions{align-items:flex-start;flex-wrap:wrap}.next-actions>div{width:100%}}@media(max-width:620px){.lesson-grid{grid-template-columns:1fr}.content-panel>header,.source-note{align-items:flex-start;flex-direction:column}}
</style>
