"""alpha_foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'f3cc62ac42cf'
down_revision = '905cf71efaee'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_items',
    sa.Column('import_key', sa.String(length=64), nullable=False),
    sa.Column('source_document_name', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('original_grade_label', sa.String(length=200), nullable=False),
    sa.Column('normalized_grade', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('raw_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_group', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_key')
    )
    op.create_table('knowledge_items',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=False),
    sa.Column('pedagogical_dimension', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=60), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('asset_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dataset_annotations',
    sa.Column('import_key', sa.String(length=64), nullable=False),
    sa.Column('dataset_item_id', sa.String(length=36), nullable=False),
    sa.Column('source_dimension', sa.Text(), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=False),
    sa.Column('evaluation', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('detailed_suggestion', sa.Text(), nullable=False),
    sa.Column('source_basis', sa.Text(), nullable=False),
    sa.Column('theoretical_basis', sa.Text(), nullable=False),
    sa.Column('teaching_method_reference', sa.Text(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('raw','reviewed','verified','rejected')"),
    sa.ForeignKeyConstraint(['dataset_item_id'], ['dataset_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_key')
    )
    op.create_table('user_preferences',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('case_items',
    sa.Column('source_dataset_item_id', sa.String(length=36), nullable=False),
    sa.Column('source_annotation_id', sa.String(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=60), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=60), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('asset_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_annotation_id'], ['dataset_annotations.id'], ),
    sa.ForeignKeyConstraint(['source_dataset_item_id'], ['dataset_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_annotation_id')
    )
    op.create_table('dataset_verifications',
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('issue_exists', sa.Boolean(), nullable=False),
    sa.Column('location_correct', sa.Boolean(), nullable=False),
    sa.Column('suggestion_actionable', sa.Boolean(), nullable=False),
    sa.Column('basis_supported', sa.Boolean(), nullable=False),
    sa.Column('worth_fixing', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['dataset_annotations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_overviews',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('lesson_overviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_overviews_user_id'), ['user_id'], unique=False)

    op.create_table('system_config_snapshots',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('system_config_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('context_snapshots',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('current_section_version_id', sa.String(length=36), nullable=False),
    sa.Column('contributor_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fragment_source_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lesson_overview_id', sa.String(length=36), nullable=True),
    sa.Column('related_section_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memory_reference_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preference_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('knowledge_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('case_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('model_provider', sa.String(length=60), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('system_config_version', sa.Integer(), nullable=False),
    sa.Column('context_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_section_version_id'], ['section_versions.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['generation_records.id'], ),
    sa.ForeignKeyConstraint(['lesson_overview_id'], ['lesson_overviews.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_id')
    )
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_snapshots_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('related_section_id', sa.String(length=36), nullable=True),
    sa.Column('related_suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['related_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['related_suggestion_id'], ['suggestions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)


    # One explicit legacy identity, never a guessed real participant identity.
    from uuid import uuid4
    legacy_id = str(uuid4())
    op.execute(sa.text("INSERT INTO users (id,username,role,created_at,updated_at) VALUES (:id,'legacy-import','user',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bindparams(id=legacy_id))
    owned = ['participants','sessions','lesson_plans','lesson_plan_versions','rounds','sections',
             'section_versions','section_reviews','generation_records','suggestions','decisions',
             'custom_prompts','retrieval_records','interaction_events']
    naming = {'uq': 'uq_%(table_name)s_%(column_0_name)s'}
    extras = {
      'suggestions': [('issue_type',sa.String(50),'other'), ('scope',sa.String(30),'local'),
         ('confidence',sa.Float(),None), ('target_text',sa.Text(),None), ('revision_mode',sa.String(20),'append'),
         ('knowledge_ids',sa.JSON().with_variant(postgresql.JSONB(),'postgresql'),'[]'),
         ('basis_sources',sa.JSON().with_variant(postgresql.JSONB(),'postgresql'),'[]')],
      'retrieval_records': [('contributor_type',sa.String(60),'legacy'), ('query_text',sa.Text(),''),
         ('filters',sa.JSON().with_variant(postgresql.JSONB(),'postgresql'),'{}'), ('retriever_type',sa.String(60),'dummy_v1'),
         ('retrieved_item_ids',sa.JSON().with_variant(postgresql.JSONB(),'postgresql'),'[]'),
         ('similarity_scores',sa.JSON().with_variant(postgresql.JSONB(),'postgresql'),'[]'), ('top_k',sa.Integer(),'0')]
    }
    for name in owned:
        checks = {
            'sessions': [("status IN ('CREATED','ACTIVE','ROUND_COMPLETED','TERMINATED')", 'ck_session_status')],
            'rounds': [("status IN ('ACTIVE','COMPLETED')", 'ck_round_status'), ('round_number BETWEEN 1 AND 5', 'ck_round_number')],
            'suggestions': [('suggestion_index BETWEEN 1 AND 2', 'ck_suggestion_index')],
            'decisions': [("decision IN ('ACCEPT','REJECT')", 'ck_decision_value')],
        }
        table_args = tuple(sa.CheckConstraint(sql, name=label) for sql, label in checks.get(name, [])) if op.get_context().dialect.name == 'sqlite' else ()
        with op.batch_alter_table(name, naming_convention=naming, table_args=table_args) as batch:
            batch.add_column(sa.Column('user_id', sa.String(36), nullable=False, server_default=legacy_id))
            batch.create_foreign_key('fk_' + name + '_user', 'users', ['user_id'], ['id'])
            batch.create_index('ix_' + name + '_user_id', ['user_id'])
            for key, kind, default in extras.get(name, []):
                batch.add_column(sa.Column(key, kind, nullable=default is None, server_default=default))
            if name == 'sessions':
                old_unique = 'sessions_request_key_key' if op.get_context().dialect.name == 'postgresql' else 'uq_sessions_request_key'
                batch.drop_constraint(old_unique, type_='unique')
                batch.create_unique_constraint('uq_sessions_user_request', ['user_id','request_key'])
        with op.batch_alter_table(name) as batch:
            batch.alter_column('user_id', existing_type=sa.String(36), server_default=None)
            for key, kind, default in extras.get(name, []):
                if default is not None: batch.alter_column(key, existing_type=kind, server_default=None)
    op.execute("INSERT INTO system_config_snapshots (id,user_id,session_id,version,config,created_at) SELECT id,user_id,id,1,config_snapshot,created_at FROM sessions")


def downgrade():
    raise RuntimeError('Alpha owns persistent research history. Restore the pre-migration backup instead of destructive downgrade.')
